name: quee_cli
description: A command line interface for quee package that provides basic argument parsing.
version: 0.0.2

repository: https://github.com/vasanth-tamil/quee_cli

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  cli_util: ^0.4.2

executables:
  quee_cli: quee

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0