name: quee_cli
version: 1.0.1

settings:
  route: lib/constants/app_routes.dart
  page: lib/pages
  controller: lib/controllers
  service: lib/services
  json: lib/models/json
  model:
    - lib/models/request
    - lib/models/response
