name: quee_cli
version: 0.0.4

settings:
  route: lib/constants/app_routes.dart
  page: lib/pages
  controller: lib/controllers
  service: lib/services
  model:
    - lib/models/request
    - lib/models/response